apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-service
  labels:
    app: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery
  template:
    metadata:
      labels:
        app: food-delivery
    spec:
      containers:
        - name: food-delivery
          image: 23MIS0432/food-delivery-order-system:latest
          ports:
            - containerPort: 8080
